### ISSUE TITLE
Add support for OpenID Connect Discovery

### ISSUE THREAD

**Issue by pedrohl97** [TDAF/passport-taccounts-oauth2#12]
Publish the information of TAccounts OpenID connect implementation in a well known location so clients can automatically get the endpoint_location, public keys to verify JWT tokens, supported flows, soppurted scopes, etc.

Here are samples of implementations from Microsoft, Google and Paypal:
https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration
https://accounts.google.com/.well-known/openid-configuration
https://www.paypal.com/.well-known/openid-configuration

And the specification
https://openid.net/specs/openid-connect-discovery-1_0.html

Best regards.

**Comment by dlozlla** [comment]
This applies to Accounts Server. Please follow this at https://github.com/TDAF/accounts/issues/344
