### ISSUE TITLE
Add support for OpenID Connect RP-Initiated logout

### ISSUE THREAD

**Issue by pedrohl97** [TDAF/passport-taccounts-oauth2#13]
Enable a logout endpoint so an application (relaying party) call force a logout in Telefonica Accounts.

Tipically this endpoint receives two parameters:
- id_token_hint: with the id_token generated for the application of the logged user
- post_logout_redirect_uri: URL the user will be redirected after the TAccout logout

It is part of the OpenID Connect Session Management specification.
http://openid.net/specs/openid-connect-session-1_0.html

Best regards.

**Comment by dlozlla** [comment]
We are about to add it to the server. Follow this at https://github.com/TDAF/accounts/issues/342. As a clarification, our current plan is to support the post_logout_redirect_uri, but not the ID_token_hint which is optional in the spec.
