### ISSUE TITLE
Forcing the reauthentication of a user in T. Accounts

### ISSUE THREAD

**Issue by pedrohl97** [TDAF/passport-taccounts-oauth2#14]
Add support for the parameter "prompt=login" in the request to the authorization endpoint to force a user authentication even if the user has an active session.

http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

Some critical applications have lower session lifetime that T. Accounts and can require the user to authenticate again.

Best regards.

**Comment by dlozlla** [comment]
This is already supported. Actually, we are about to add support for prompt=none. Please follow issues at  https://github.com/TDAF
